### ISSUE TITLE
Selfie Events are creating NaN's

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#308] opened 2015-09-20 21:39 UTC
How to fix Tieteasha Adderley's NaN - she's really concerned :) - and how to keep it from happening?
![messages image 1899120158](https://cloud.githubusercontent.com/assets/7445103/9983042/7f8a3e76-5fbe-11e5-8ac7-a2075e088d7e.png)

**Comment by drenfr01** [comment] 2015-09-21 00:21
@drewproud @unioncapitalboston @ballek 

Hi All, so I did some poking around and the issue is similar to the one Drew described in an email a week ago. However, Eric as you mentioned in your follow up email, this also seems to have happened for selfie events. 

It looks like 4 members are affected right now, but what's odd is that I can only find 3 transactions where the points are NaN.

**Comment by drenfr01** [comment] 2015-09-21 00:26
Looking at Cleia, we seem to have a larger issue. One of her NaN points transactions is as Drew described, where there are no points. However, the other one, "First Teacher Fall Fun Fair", has both pointsPerHour and duration, so it should be calculating fine. But yet, it's not showing up...

**Comment by drenfr01** [comment] 2015-09-21 00:35
Of the four members who have NaN points...

Teteasha Adderley, Elsa Flores, Dioneiris Medrano all have points clearly marked as NaN. Teteasha & Elsa have selfie events, which means that somehow during the approval process either someone didn't enter points or it was dropped.

Cleia Borges simply had a points per hour event, which weren't displaying correctly.

**Comment by drenfr01** [comment] 2015-09-21 00:36
So, long story short: Drew's fixes should avoid a repeat of the issues for the first 3 members, and will immediately fix Cleia Borges' account.

However, I'll need to go into the events and manually add points to them. @unioncapitalboston @ballek , should I just hop on the phone with one of you?

**Comment by drenfr01** [comment] 2015-09-21 00:46
also, added in a check to make sure admins never approve an event with a blank number of points (although 0 is allowed)

**Comment by ballek** [comment] 2015-09-22 20:22
@drenfr01 & @drewproud  this issue is almost undoubtedly my fault. i think it's related to issue #296-- i sort of stopped entering numbers in the "points" column of the csv upload. i'm not sure why i did that, but i see now it was an error. I WON'T DO IT ANYMORE! 

however, i'm trying to edit the offending events in houston but it keeps crashing on me because 'transactions' is too big. plz advise.

**Comment by drewproud** [comment] 2015-09-23 22:18
@ballek As long as you promise not to do it again, I can show you how to use RoboMongo to access the DB directly over a Google Hangout. Shoot me an email when you're free.

**Comment by drenfr01** [comment] 2015-10-14 03:51
@ballek @unioncapitalboston I believe this is closed?

**Closed** 2016-02-21 21:28 UTC
Labels: bug
