### ISSUE TITLE
The 2 fixes that need to occur ASAP so we don't go bankrupt :/

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#456] opened 2017-02-06 14:53 UTC
Thank you again Duncan and Drew for working on the App during Super Bowl Sunday! I was tied up with my family and am just catching up now. If you are able this week or weekend to make these two fixes, we will breathe a huge sigh of relief and save a lot of our limited Rewards money. Hopefully you've already made headway on both, but I am listing them both here so they move to the top of your priorities if possible:

1) All Selfie submissions 2 hours or more MUST NEVER auto-approve and HAVE TO filter to Super Admin for approval. No matter what the category or activity is, **please have all Selfies 2 or more hours never auto-approve**. The big fix is that "OTHER" category I just posted about.

2) In Super Admin, we are unable to change the value of the Event Points that process. This means that if someone submits 8 hours for exercise it comes for approval for 800 points. If we go into the box, change it to 100 points and click submit, it still puts 800 Points in their account. Can you please fix so that Super Admin can set the final points value no matter what is submitted by the User?

THANK YOU THANK YOU!

**Comment by drewproud** [comment] 2017-02-06 16:19
Got myself a new laptop, so I'm going to get UCB up and working on my
laptop tonight and get this figured out.

**Comment by unioncapitalboston** [comment] 2017-02-06 16:40
Love you Guyz!

**Comment by drenfr01** [comment] 2017-02-07 12:41
@drewproud I have an hour or two tonight I'll throw at point #2. Thanks for getting the ball rolling!

**Comment by unioncapitalboston** [comment] 2017-02-09 21:36
Thank you DunDrew Crew! It is looking like the Rule Change has worked!!

How is the second fix looking? Now that we have more to manually approve it will be very valuable to not have to enter in points for each entry as we have to now, and also be able to adjust points based on correct amounts, which we can't do yet.

I leave for Taiwan tomorrow with my family to visit Jenny's parents, so Laura is Large & In Charge while I'm gone :)

Thank you again and... HAPPY BIRTHDAY TOMORROW DUNCAN!!

**Comment by drenfr01** [comment] 2017-02-09 23:21
@unioncapitalboston @ballek @drewproud 

I fixed the issue with the inability to change the points with selfie events. However, by design all pre-planned (i.e. non-selfie) events could not have their points altered (instead you would change the event points in the "manage events" page). I assume this is still correct?

**Comment by unioncapitalboston** [comment] 2017-02-10 03:22
That is correct! Thank you!

The final bit is 'unfreezing' the Points boxes so we don't have to go in and reenter points just to be able to click the Approve box.

**Comment by ballek** [comment] 2017-02-10 03:29
@drenfr01 I think the issue with pre-planned events is that, say an event is planned for 8 hours, and a member only attends for 2 hours, right now would they be getting the full 800 points?

**Comment by drenfr01** [comment] 2017-02-10 17:29
@unioncapitalboston @ballek correct, so now you can change any event that is "points per hour". Things that are fixed points though, like let's say a scheduled 1 hour meeting, have to be edited through the actual event.

**Comment by drenfr01** [comment] 2017-02-10 17:31
@unioncapitalboston @ballek I'm deploying now the fix for editing events. Eric & Laura, next week I'll tackle the unfreezing the points box thing (I'm on VK this weekend as well).

Enjoy Thailand!!!

**Comment by ballek** [comment] 2017-02-10 20:06
@drenfr01 thanks Duncan. Enjoy your vacay, and let me use one more platform to wish you a HAPPY BIRTHDAY!!!!!!!

**Comment by drenfr01** [comment] 2017-02-10 20:13
Ahh, thanks!

**Comment by drewproud** [comment] 2017-03-07 02:50
@ballek we good to close this issue? The freezing should be covered in #461

**Comment by ballek** [comment] 2017-03-07 06:11
@drewproud BALLIN'

**Closed by ballek** 2017-03-07 06:11 UTC
